baseURL            = "https://benjamin-thomas.github.io/blog/"
languageCode       = "en-us"
title              = "Notes about programming"
theme              = "hugo-theme-bleak"
PygmentsCodeFences = true
publishDir         = "docs"
comments = true

[params]
  # Warning Keys are case sensitives
  #Subtitle = "Your subtitle !"
  #description = "Everything is awesome !"
  #cover = "/images/cover.jpg"

  # Google analytics
  #googleAnalyticsUserID = "UA-xxxxxxxx-x"
  #domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "benjamin-thomas-github-io"
