baseURL            = "https://benjamin-thomas.github.io/"
languageCode       = "en-us"
title              = "Programming, etc."
theme              = "m10c"
PygmentsCodeFences = true
publishDir         = "../benjamin-thomas.github.io"
comments = true


[params]
  name = "Benjamin THOMAS"
  description = " "
  # Warning Keys are case sensitives
  #Subtitle = "Your subtitle !"
  #description = "Everything is awesome !"
  #cover = "/images/cover.jpg"

  # Google analytics
  #googleAnalyticsUserID = "UA-xxxxxxxx-x"
  #domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "benjamin-thomas-github-io"

[[params.social]]
  name = "github"
  url = "https://github.com/benjamin-thomas"
