baseURL            = "github.com/benjamin-thomas"
languageCode       = "en-us"
title              = "Notes about programming"
theme              = "hugo-theme-bleak"
PygmentsCodeFences = true
publishDir         = "docs"
