baseURL            = "https://benjamin-thomas.github.io/"
languageCode       = "en-us"
title              = "Notes about programming"
theme              = "m10c"
PygmentsCodeFences = true
publishDir         = "../benjamin-thomas.github.io"
comments = true

[params]
  # Warning Keys are case sensitives
  #Subtitle = "Your subtitle !"
  #description = "Everything is awesome !"
  #cover = "/images/cover.jpg"

  # Google analytics
  #googleAnalyticsUserID = "UA-xxxxxxxx-x"
  #domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "benjamin-thomas-github-io"

 [params.author]
    firstName = "Benjamin"
    lastName = "Thomas"
    gender = "male"
    github = "benjamin-thomas"
    gravatarHash = "36ba49b97bcebe6efe7e507a3cd3029f"
